export default {
  home: "/",
  search: "/s",
  listings: "/l",
  ListingCreatePage: "/l/create",
  listingDetails: "/l",
  listingCreate: "/l/create",
  listingEdit: "/l/edit",
  signin: "/signin",
  signup: "/signup",
  userBookmark: "/u/bookmark",
  userDashboard: "/u/dashboard",
  userListing: "/u/listing",
  userAccount: "/u/account",
  userSetting: "/u/setting",
  userMediaSetting: "/u/setting/media",
  userSecuritySetting: "/u/setting/security",
  userSocialSetting: "/u/setting/social",
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  policy: "/policy",
};
