export default {
  home: "/",
  listings: "/l",
  listingDetails: "/l",
  signin: "/signin",
  signup: "/signup",
  userBookmark: "/bookmark",
  userDashboard: "/dashboard",
  userListing: "/listing",
  userProfile: "/profile",
  userSetting: "/setting",
  userMediaSetting: "/setting/media",
  userSecuritySetting: "/setting/security",
  userSocialSetting: "/setting/social",
  about: "/about",
  contact: "/contact",
  faq: "/faq",
  policy: "/policy",
};
