import UserLayout from "src/layouts/UserLayout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  viewport: "initial-scale=1, width=device-width",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <main>
      <UserLayout>{children}</UserLayout>
    </main>
  );
}
